export enum AppEnumConstants {
  STATUS_PENDING = 'P',
  STATUS_OPEN = 'O',
  STATUS_ACTIVE = 'AS',
  STATUS_INACTIVE = 'IS',
  STATUS_REJECT = 'R',
  STATUS_APPROVED = 'A',
  STATUS_COMMON = 'C',
  STATUS_VOID = 'V',
  LABEL_PENDING = 'PENDING',
  LABEL_REJECT = 'REJECTED',
  LABEL_APPROVED = 'APPROVED',
  LABEL_VOID = 'VOID',
}
